### ISSUE TITLE
React-dom development server large part of bundle

### ISSUE THREAD

**Issue by JackHowa** [WPMedia/engine-theme-sdk#283]
<img width="942" alt="Screen Shot 2021-04-06 at 14 18 08" src="https://user-images.githubusercontent.com/5950956/113766680-50118480-96e3-11eb-845b-70eb2a0ded80.png">

-> suggestion in tech grooming was to use it as peer dep

**Comment by JackHowa** [comment]
failed as peer dep: 

```
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/utils/localizeDate.test.ts
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/components/Image/image.test.jsx
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/components/VideoPlayer/index.test.tsx
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/utils/extractVideoEmbedFromStory.test.ts
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/components/Image/thumbor-image-url.test.ts
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/components/Image/SourceHandler.test.tsx
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/components/ArcLogo/index.test.tsx
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/utils/isValidDateFormatString.test.ts
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/components/ErrorBoundary/index.test.tsx
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/components/EventEmitter/index.test.tsx
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/utils/serverSide.test.ts
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      jest/testSetupFile.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/components/VideoPlayer/index-ssr.test.tsx
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

**Comment by JackHowa** [comment]
may still need it: 

```jsx

const generateCustomMetaTags = (metaData, MetaTag, MetaTags): ReactElement => {
  const metaHTMLString = ReactDOMServer.renderToString(<MetaTags />);
  const customMetaData = getCustomMetaData(metaHTMLString)
    .filter((metaObj) => !metaData[metaObj.metaName]);
  return (
    <>
      {customMetaData.length > 0 && customMetaData.map((metaObj, i) => (
        // eslint-disable-next-line react/no-array-index-key
        <MetaTag key={`custom-meta-data-${i}`} name={metaObj.metaName} default={metaObj.metaValue} />
      ))}
    </>
  );
};

```

**Comment by JackHowa** [comment]
I wonder if the node_env is not being set to production. When I set it locally and try to use `-p` for production fusion build, it still shows as the much larger development build of react dom

**Comment by badmintonkid** [comment]
How are you testing? I believe react checks for `NODE_ENV`. If you are looking to have fusion serve the right version, you are going to have to run `npm run build:prod`.

**Comment by JackHowa** [comment]
will give that a shot, thanks @badmintonkid

**Comment by badmintonkid** [comment]
Cool, let me know if you have issues and I can help investigate.

**Comment by JackHowa** [comment]
react-dom server is required for engine theme sdk. not applicable
